version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      # install dependencies in both apps
      - run:
          name: hello
          command: |
            echo "hello-world"
      - run:
          name: Install NPM (manual fallback)
          command: |
            echo "Attempting manual npm install as fallback"
            sudo npm install -g npm@latest
